const wordlist = {
    "ABS": "Ärende- och beslutsstöd",
    "ABU": "Aktivitetsbaserad utredning (av arbetsförutsättningar/arbetsförmåga)",
    "AMPB": "Arbetsmarknadspolitisk bedömning",
    "AD": "Annonsera direkt",
    "Af": "Arbetsförmedlingen",
    "AFD": "Aktiviteter inom vägledning",
    "AFID": "Arbetsförmedlingens inriktningsdokument",
    "AFI": "Arbetsförmedlingen internet",
    "AFII": "Arbetsförmedlingens interna instruktioner",
    "AFLI": "Arbetsförmedlingen levererar information",
    "AG": "Arbetsgivare",
    "AIP": "Arbetssökandes inskrivning och planering",
    "AIS": "Arbetsförmedlingens informationssystem",
    "ANB": "Anordnarbidrag",
    "APR": "Arbetspraktik",
    "APL": "Arbetsplatsförlagt lärande (praktik under utbildning)",
    "APT": "Arbetsplatsträff",
    "APU": "Arbetspsykologisk utredning",
    "AR": "Arbetslivsinriktad rehabilitering",
    "ARB": "Arbetsträning (gammal förkortning)",
    "ASÖK": "Arbetssökande",
    "AT": "Arbetsträning",
    "ATH": "Arbetsträning med handledare",
    "AUB": "Arbetsmarknadsutbildning",
    "AVUS": "Avtalsdatabas och uppföljning",
    "BFB": "Beslut om stöd till personligt biträde",
    "BHA": "Bidrag till hjälpmedel på arbetsplatsen",
    "BHTJ": "Behörighetstjänsten",
    "BOI": "Beslut om insats",
    "BSN": "Bidrag till uppstartskostnader vid start av näringsverksamhet",
    "BÄR": "Beslut- och ärendehanteringssystem",
    "CAK": " Central arbetsgivarkontroll",
    "CR": "Chefsrummet",
    "CRM": "Customer relationship management, det vill säga kundrelationssystem",
    "DXA": "Direktöverförda annonser (i Platsbanken)",
    "EEP": "Etableringsersättning (gammal förkortning)",
    "EES": "Etableringsersättningssystemet",
    "EGK": "Enheten Granskning och kontroll",
    "EKA": "Ekonomiskt stöd till kompletterande aktör",
    "EPA": "Etableringsplan",
    "EKI": "Effektiv kundintegritet",
    "ELIN": "Elektronisk interimslösning (för digital hantering av dokument)",
    "ESF": "Europeiska socialfonden",
    "ETP": "Etableringsprogrammet",
    "EVP": "Arbetsgivarerbjudande (employer value proposition)",
    "FAM": "Flexibla anpassningsmoduler",
    "FAT": "Förstärkt arbetsträning",
    "FKV": "Fördjupad kartläggning och vägledning",
    "FSAS": "Förstärkt särskilt anställningsskydd (gammal förkortning)",
    "FUB": "Förberedande utbildning",
    "FUT": "Felaktig utbetalning",
    "GFR": "Gemensamt företagsregister",
    "GUP": "Gemensam utbildningsplan",
    "HFU": "Hörselfunktionsutredning",
    "HL": "Handläggare",
    "HS": "Handläggarstöd",
    "INAB": "Introduktion till arbete",
    "INJ": " Introduktionsjobb",
    "INTRO": "Introduktionsjobb",
    "IPSU": "Individuellt pedagogiskt stöd vid utbildning",
    "ITA": "Insats för klargörande av arbetsförutsättning/arbetsförmåga",
    "JOB": "Jobb- och utvecklingsgarantin",
    "KA": " Kompletterande aktör",
    "KAP": "Kundarbetsplats",
    "KROM": "Kundval Rusta och matcha (undvik: säg enbart Rusta och matcha)",
    "KVL": "Karriärvägledning",
    "KVR-V": "Förberedande insats - vägledande inriktning",
    "KVR-R": "Förberedande insats - rehabiliteringsinriktning",
    "KVR-K": "Förberedande insats - kartläggning",
    "LBG": "Lönebidrag",
    "LEV": "Leverantörsavrop",
    "LFA": "Lönebidrag för anställning",
    "LFT": "Lönebidrag för trygghet i anställning",
    "LFU": "Lönebidrag för utveckling i anställning",
    "LOU": "Lagen om offentlig upphandling",
    "LOV": "Lagen om valfrihetssystem",
    "MBJ": "Moderna beredskapsjobb",
    "MER": "Merkostnadsersättning till anordnare vid viss arbetsträning",
    "MLG": "Myndighetens ledningsgrupp",
    "MU": "Medicinska underlag",
    "MVP": "Minsta livskraftiga produkt (minimum viable product)",
    "NEPT": "Nationell expert under professionell utbildning (tjänstgöring inom EU för handläggare på huvudkontoret)",
    "NOR": "Nit och redlighet i rikets tjänst (utmärkelse för dig som jobbat i staten minst 30 år)",
    "NYJ": "Nystartsjobb",
    "NYJ(S)": "Särskilt nystartsjobb",
    "OSA": "Offentligt skyddat arbete",
    "OSA2": "Organisatorisk och social arbetsmiljö",
    "PDM": "Personligt distansmöte",
    "PISA": "Plattform för identifiering och signering på Arbetsförmedlingen",
    "PWM": "Personliga webbmöten",
    "PiA": "Patientjournalsystem inom Arbetsförmedlingen",
    "PRGM": "Programresebeslut",
    "RA": "Riktad arbetspsykologisk utredning",
    "RAI": "Redovisning av insats",
    "RES": "Intervjuresa",
    "SAA": "Systemstöd anskaffande arbetsförmedlingstjänster",
    "SAE": "Systematiserat arbetssätt inom etableringen",
    "SAM": "Systematiskt arbetsmiljöarbete",
    "SAS": "Särskilt anställningsstöd (gammal förkortning)",
    "SEB": "Start av näringsverksamhet",
    "SEM": "Sökmotormarknadsföring (search engine marketing)",
    "SEO": " Sökmotoroptimering (search engine optimization)",
    "SFI": "Svenska för invandrare",
    "SFU": "Synfunktionsutredning",
    "SIA": "Samlad intern arbetsyta",
    "SMF": "Folkhögskoleutbildning i studiemotiverande syfte",
    "SPC": "Specialistinsats",
    "SIUS": "Särskilt introduktions- och uppföljningsstöd",
    "SSC": "Statens servicecenter",
    "SSM": "Service system manager (systemstöd för dokumenthantering)",
    "SSYK": "Standard för svensk yrkesklassificering (ett system för gruppering av yrken)",
    "STOM": "Stöd och matchning",
    "SÖK": "Arbetssökande",
    "SÖK-A": "Söka arbetssökande (systemstöd för att söka arbetssökande)",
    "UGA": "Jobbgarantin för ungdomar",
    "UBK": "Utbildningskontrakt",
    "UR": "Uppföljningsrapport",
    "UTA": "Utbildningsanvisning",
    "VAL": "Validering",
    "VIS": "Våra informationssidor (Arbetsförmedlingens intranät)",
    "VO": "Verksamhetsområde",
    "VPN": "Virtual private network",
    "YA": "Yrkesintroduktionsanställning (arbetsmarknadsdepartementets förkortning)",
    "YKB": "Yrkeskompetensbedömning",
    "YRI": "Yrkesintroduktion/yrkesintroduktionsanställning",
    "YSM": "Yrkes- och studieförberedande moduler",
    "PR": "Periodisk rapport, skickas in av Leverantörer för att möjliggöra fakturering",
    "GP": "Gemensam planering, deltagaren och Leverantörens planering för insatsen, krävs för att beslutet ska kunna attesteras och faktureras",
    "SR": "Slutrapport",
    "ka webb": "Ingång till KA för externa leverantörer av insatser",
    "ka webbstöd": "Ingång till KA för interna användare - arbetsförmedlare etc",
    "dafa": "Efterföljaren till KA",
    "självfaktura": "",
    "snow": "Service Now, ärendehanteringssystem för felanmälningar",
    "kb": "Knowledgebase, syftar oftast på en artikel med problem- och lösningsbeskrivning",
    "inc": "Incident, INC tillsammans med 7 siffror syftar på ett specifikt ärende/incident i Servicenow",
    "aveksa": "Verktyg för att arbeta med eller kontrollera behörigheter för användare",
    "PR": "Periodisk rapport",
    "IR": "Informativ rapport"

}